#:schema node_modules/wrangler/config-schema.json
name = "cs-mentor-worker"
main = "src/index.js"

account_id = "50765bc3a2614926f28f559a6216ec3e"
workers_dev = true
compatibility_date = "2024-09-19"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "USER_DATA"
id = "e563012b453e4ae7b0179aabff69644c"